services:
    phpunit-8-1:
        build: ./docker/php-8.1
        networks:
            - query-builder-test
        volumes:
            - ./:/var/www
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9000 log=/tmp/xdebug/xdebug.log output_dir=/tmp/xdebug start_with_request=trigger"
            XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    phpunit-8-3:
        build: ./docker/php-8.3
        networks:
            - query-builder-test
        volumes:
            - ./:/var/www
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9000 log=/tmp/xdebug/xdebug.log output_dir=/tmp/xdebug start_with_request=trigger"
            XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    phpunit-8-4:
        build: ./docker/php-8.4
        networks:
            - query-builder-test
        volumes:
            - ./:/var/www
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9000 log=/tmp/xdebug/xdebug.log output_dir=/tmp/xdebug start_with_request=trigger"
            XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql57:
        image: mysql:5.7
        restart: 'no'
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 9601:3306
        networks:
            - query-builder-test
    mysql80:
        image: mysql:8
        restart: 'no'
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 9602:3306
        networks:
            - query-builder-test
    mariadb11:
        image: mariadb:11.1.3
        restart: 'no'
        environment:
            MYSQL_DATABASE: test_db
            MARIADB_ROOT_PASSWORD: password
        ports:
            - 9603:3306
        networks:
            - query-builder-test
    postgresql10:
        image: postgres:10
        restart: 'no'
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 9604:5432
        networks:
            - query-builder-test
    postgresql16:
        image: postgres:16
        restart: 'no'
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 9605:5432
        networks:
            - query-builder-test
    sqlsrv2019:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: 'no'
        environment:
            ACCEPT_EULA: "y"
            MSSQL_PID: Developer
            MSSQL_SA_PASSWORD: P@ssword123
            SA_PASSWORD: P@ssword123
        ports:
            - 9606:1433
        networks:
            - query-builder-test
    sqlsrv2022:
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: 'no'
        environment:
            ACCEPT_EULA: "y"
            MSSQL_PID: Developer
            MSSQL_SA_PASSWORD: P@ssword123
            SA_PASSWORD: P@ssword123
        ports:
            - 9607:1433
        networks:
            - query-builder-test

networks:
    query-builder-test:
